name: Deploy Voll Med

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configura JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Verifica Docker Compose
        run: docker compose version

      - name: Roda Docker Compose
        run: docker compose up -d

      - name: Verifica imagem criada
        run: docker images vollmed-api

      - name: Deploy para EC2
        env:
          PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
          USER: ubuntu
          HOST: 54.174.175.145
        run: |
          echo "$PRIVATE_KEY" > deploy_key.pem
          chmod 600 deploy_key.pem

          docker save -o vollmed-api.tar vollmed-api:latest

          scp -o StrictHostKeyChecking=no -i deploy_key.pem vollmed-api.tar $USER@$HOST:/home/ubuntu/
          scp -o StrictHostKeyChecking=no -i deploy_key.pem init.sql $USER@$HOST:/home/ubuntu/
          scp -o StrictHostKeyChecking=no -i deploy_key.pem docker-compose-prod.yaml $USER@$HOST:/home/ubuntu/
          scp -o StrictHostKeyChecking=no -i deploy_key.pem script-deploy.sh $USER@$HOST:/home/ubuntu/

          ssh -o StrictHostKeyChecking=no -i deploy_key.pem $USER@$HOST \
            "chmod +x script-deploy.sh && ./script-deploy.sh"
